---
- name: Wait for FortiGate to be ready
  wait_for:
    host: "{{ ansible_host }}"
    port: 443
    delay: 15
    timeout: 60
  register: result
  retries: 5
  delay: 30
  until: result is success

- name: Set hostname
  fortios_system_global:
    vdom: "root"
    system_global:
      hostname: "{{ fgt1_hostname }}"
  register: result
  until: result is success
  retries: 10
  delay: 15

- name: Set timezone
  fortios_system_global:
    vdom: "root"
    system_global:
      timezone: "26"
  register: result
  until: result is success
  retries: 5
  delay: 10
